<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.qoop</groupId>
        <artifactId>qoop-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>ir.tamin</groupId>
    <artifactId>hub</artifactId>
    <packaging>pom</packaging>
    <version>0.0.1-SNAPSHOT</version>

    <modules>
        <module>hub-domain</module>
        <module>hub-application</module>
        <module>hub-infrastructure</module>
        <module>hub-presentation</module>
        <module>hub-container</module>
    </modules>

    <properties>
        <identity.version>0.0.1-SNAPSHOT</identity.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ir.tamin</groupId>
                <artifactId>hub-domain</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>ir.tamin</groupId>
                <artifactId>hub-application</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
