server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: hub
  main:
    banner-mode: off
  profiles:
    active: @spring.profiles.active@

  datasource:
    url: jdbc:oracle:thin:@//DB3RH:1521/setadidevdb.tamin.org
    username: acc115597
    password: account

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none  # (validate, update, create, create-drop)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

  threads:
    virtual:
      enabled: true

discovery:
  service:
    host: ${CONSUL_SERVICE_HOST:localhost}
    port: ${CONSUL_SERVICE_PORT:6060}
    token: ${CONSUL_SERVICE_TOKEN:24e33f73-3726-6c32-0e62-6f226b18a9ce}
  self:
    prefer-ip-address: ${SELF_PREFER_IP_ADDRESS:false}
    ip-address: ${SELF_IP_ADDRESS:192.168.30.100}
    port: ${SELF_PORT:${server.port}}

doc:
  title: Hub
  version: @project.version@
  description: Hub for Payment ...
  server:
    url: /api

scan:
  packages: ir.tamin