<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.qoop</groupId>
        <artifactId>qoop-container</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>hub-container</artifactId>

    <properties>
        <hub.version>0.0.1-SNAPSHOT</hub.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>ir.tamin</groupId>
            <artifactId>hub-infrastructure</artifactId>
            <version>${hub.version}</version>
        </dependency>

        <dependency>
            <groupId>ir.tamin</groupId>
            <artifactId>hub-presentation</artifactId>
            <version>${hub.version}</version>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-e2e-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
