<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ir.tamin</groupId>
        <artifactId>hub</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>hub-domain</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-transaction-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-bean-filter-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-domain</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-fault-handler-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-filter-wrapper-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-logs-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-security-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-utils-api</artifactId>
        </dependency>
    </dependencies>
</project>
